- name: Install Datadog Agent
  hosts: node 
  become: yes
  user: ubuntu 
  
- name: Dowload Datadog role for GitHub
  get_url:
    url: https://github.com/DataDog/ansible-datadog/archive/refs/heads/master.zip
    dest: /tmp/datadog.zip
