- name: Install Datadog Agent
  hosts: node 
  become: yes
  user: ubuntu 
  tasks:
    - name: Install Ansible 
      apt:
        name: ansible 
        state: present 
        update_cache: yes

    - name: Download the role 
      get_url:
        url: https://github.com/DataDog/ansible-datadog/archive/refs/heads/master.zip
        dest: /tmp/datadog.zip
    
    - name: Unzip the role 
      unarchive:
        src: /tmp/datadog.zip
        dest: /root/.ansible/roles/Datadog.datadog
        remote_src: yes
